name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        file: ./dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dummywebapp:${{ github.sha }}

    - name: Run Trivy vulnerability scanner (Pipeline Output)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_HUB_USERNAME }}/dummywebapp:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        
    - name: Run Trivy vulnerability scanner (Sarif Output)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref:  '${{ secrets.DOCKER_HUB_USERNAME }}/dummywebapp:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always() 
      with:
        sarif_file: 'trivy-results.sarif'
      
    - name: Build and push
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dummywebapp:${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/dummywebapp:latest
